# Generated by Django 2.0.5 on 2019-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('information', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('path_photos', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
